// Generates bin/modules.mjs: the ambient module specifiers declared by the
// packaged .d.ts files, used by the ovrc-build bin to emit esbuild --external
// flags. Run by mise/tasks/package-js after the .d.ts files are copied in.
import { Glob } from "bun";
import { parse, types } from "recast";
import tsParser from "recast/parsers/typescript";

// ASTNode, not Node: it is the discriminated union, so narrowing on .type works.
type ASTNode = types.namedTypes.ASTNode;
type TSModuleBlock = types.namedTypes.TSModuleBlock;

const root = new URL("..", import.meta.url).pathname;

// An ambient module is only importable if it actually exports something; a
// declaration that only augments globals is not a bundler input.
const exportsSomething = (block: TSModuleBlock) =>
  block.body.some((node) =>
    [
      "ExportNamedDeclaration",
      "ExportDefaultDeclaration",
      "ExportAllDeclaration",
    ].includes(node.type),
  );

// Recurse so nested and namespace-wrapped declarations are found too.
function collect(nodes: ASTNode[], found: Set<string>) {
  for (const node of nodes) {
    if (
      node.type !== "TSModuleDeclaration" ||
      node.body?.type !== "TSModuleBlock"
    )
      continue;
    if (node.id.type === "StringLiteral" && exportsSomething(node.body))
      found.add(node.id.value);
    collect(node.body.body, found);
  }
}

export function modulesWithExports(source: string): string[] {
  const found = new Set<string>();
  // recast's parse() is typed `any`; the TS parser always yields a File.
  const file = parse(source, { parser: tsParser }) as types.namedTypes.File;
  collect(file.program.body, found);
  return [...found];
}

if (import.meta.main) {
  const found = new Set<string>();
  for (const file of new Glob("js_modules/**/*.d.ts").scanSync(root)) {
    for (const name of modulesWithExports(await Bun.file(root + file).text()))
      found.add(name);
  }
  const modules = [...found]
    .map((m) => {
      let sortName = m;
      if (sortName.startsWith("ovrc:")) {
        sortName = sortName.slice("ovrc:".length);
      }

      return {
        sortName,
        moduleName: m,
      };
    })
    .toSorted((a, b) => {
      return a.sortName.localeCompare(b.sortName);
    })
    .map((v) => {
      return `/* ${v.sortName} */ "${v.moduleName}"`;
    })
    .join(",\n");
  await Bun.write(
    root + "bin/modules.mjs",
    `// Auto-generated by scripts/generate-modules.ts. Do not edit.\nexport default [\n${modules}\n];\n`,
  );
  console.log(`bin/modules.mjs: ${modules.length} modules`);
}
