[book]
title = "OvrC Integration Developer Documentation"
authors = ["ADI Global"]
language = "en"
src = "content"

[output.html]
git-repository-url = "https://github.com/snap-one/ovrc-integration"
# copied over from hugo static, some custom styling of some elements
additional-css = ["content/_static/main.css"] 
additional-js = [ "content/_static/mermaid.min.js", "content/_static/mermaid-init.js", "content/_static/valid-edit-urls.js"]
edit-url-template = "https://github.com/snap-one/ovrc-integration/edit/release-candidate/docs/pages/hugo/{path}"

[output.html.print]
enable = false

[output.html.fold]
enable = false    # whether or not to enable section folding
level = 0         # the depth to start folding

[output.linkcheck2]
exclude = []

[preprocessor.mermaid]

