#!/usr/bin/env bash

#MISE description="Run all typescript tests"
set -euo pipefail

cd typescript
for dir in */; do
  name="${dir%/}"
  case "$name" in
  mise | node_modules) continue ;;
  esac

  cd $name
  bun i
  bun test --pass-with-no-tests
  cd ..
done
